In [8]:
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.optim as optim
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [3]:
df.drop(['id', 'Unnamed: 32'], inplace=True, axis=1)
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [4]:
X_train, X_test, y_train, y_test = train_test_split(df.drop('diagnosis', axis=1), df['diagnosis'], test_size=0.2, random_state=42)

In [5]:
scaler = StandardScaler();
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [6]:
lebelEncoder = LabelEncoder()
y_train = lebelEncoder.fit_transform(y_train)
y_test = lebelEncoder.transform(y_test)

In [40]:
X_train_tensor = torch.tensor(X_train, dtype=torch.float32)
X_test_tensor = torch.tensor(X_test, dtype=torch.float32)
y_train_tensor = torch.tensor(y_train, dtype=torch.float32)
y_test_tensor = torch.tensor(y_test, dtype=torch.float32)

In [56]:
class Model(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(num_features, 32),
        nn.ReLU(),
        nn.Linear(32, 1),
        nn.Sigmoid()
    )

  def forward(self, X):
    return self.network(X)

In [57]:
loss_function = nn.BCELoss()
epochs = 100

In [58]:
model = Model(X_train_tensor.shape[1])
optimizer = optim.Adam(model.parameters(), lr=0.001)

for epoch in range(epochs):
  y_pred = model.forward(X_train_tensor)

  loss = loss_function(y_pred, y_train_tensor.view(-1, 1))

  optimizer.zero_grad()

  loss.backward()

  optimizer.step()

  print(f'Epoch: {epoch} Loss: {loss.item()}')

Epoch: 0 Loss: 0.6545635461807251
Epoch: 1 Loss: 0.6407562494277954
Epoch: 2 Loss: 0.6272907853126526
Epoch: 3 Loss: 0.6141640543937683
Epoch: 4 Loss: 0.6013391017913818
Epoch: 5 Loss: 0.588821530342102
Epoch: 6 Loss: 0.5766199827194214
Epoch: 7 Loss: 0.5647498965263367
Epoch: 8 Loss: 0.5531839728355408
Epoch: 9 Loss: 0.5419360399246216
Epoch: 10 Loss: 0.5309785604476929
Epoch: 11 Loss: 0.5202429294586182
Epoch: 12 Loss: 0.5097640156745911
Epoch: 13 Loss: 0.49954861402511597
Epoch: 14 Loss: 0.48959821462631226
Epoch: 15 Loss: 0.4799167215824127
Epoch: 16 Loss: 0.4704926609992981
Epoch: 17 Loss: 0.46132493019104004
Epoch: 18 Loss: 0.4524041414260864
Epoch: 19 Loss: 0.4437074661254883
Epoch: 20 Loss: 0.43522635102272034
Epoch: 21 Loss: 0.4269699156284332
Epoch: 22 Loss: 0.41893190145492554
Epoch: 23 Loss: 0.41110900044441223
Epoch: 24 Loss: 0.40349066257476807
Epoch: 25 Loss: 0.3960795998573303
Epoch: 26 Loss: 0.3888576626777649
Epoch: 27 Loss: 0.3818238377571106
Epoch: 28 Loss: 0.37498292326927185
Epoch: 29 Loss: 0.36830806732177734
Epoch: 30 Loss: 0.361804336309433
Epoch: 31 Loss: 0.35546743869781494
Epoch: 32 Loss: 0.3492889702320099
Epoch: 33 Loss: 0.3432648777961731
Epoch: 34 Loss: 0.3373880684375763
Epoch: 35 Loss: 0.33165785670280457
Epoch: 36 Loss: 0.3260740041732788
Epoch: 37 Loss: 0.3206215798854828
Epoch: 38 Loss: 0.3152964115142822
Epoch: 39 Loss: 0.3100999891757965
Epoch: 40 Loss: 0.3050323724746704
Epoch: 41 Loss: 0.3000890910625458
Epoch: 42 Loss: 0.29527097940444946
Epoch: 43 Loss: 0.2905704975128174
Epoch: 44 Loss: 0.28598177433013916
Epoch: 45 Loss: 0.281505286693573
Epoch: 46 Loss: 0.2771369218826294
Epoch: 47 Loss: 0.2728775441646576
Epoch: 48 Loss: 0.26872673630714417
Epoch: 49 Loss: 0.2646753191947937
Epoch: 50 Loss: 0.260726660490036
Epoch: 51 Loss: 0.2568768858909607
Epoch: 52 Loss: 0.2531225085258484
Epoch: 53 Loss: 0.24945901334285736
Epoch: 54 Loss: 0.2458866983652115
Epoch: 55 Loss: 0.2424020916223526
Epoch: 56 Loss: 0.23900769650936127
Epoch: 57 Loss: 0.235697939991951
Epoch: 58 Loss: 0.2324683517217636
Epoch: 59 Loss: 0.2293146550655365
Epoch: 60 Loss: 0.22623653709888458
Epoch: 61 Loss: 0.22323274612426758
Epoch: 62 Loss: 0.22030147910118103
Epoch: 63 Loss: 0.21744005382061005
Epoch: 64 Loss: 0.2146485149860382
Epoch: 65 Loss: 0.21192650496959686
Epoch: 66 Loss: 0.20927086472511292
Epoch: 67 Loss: 0.2066803127527237
Epoch: 68 Loss: 0.20415227115154266
Epoch: 69 Loss: 0.20168745517730713
Epoch: 70 Loss: 0.19928406178951263
Epoch: 71 Loss: 0.1969359666109085
Epoch: 72 Loss: 0.19464188814163208
Epoch: 73 Loss: 0.19240152835845947
Epoch: 74 Loss: 0.1902158111333847
Epoch: 75 Loss: 0.18808075785636902
Epoch: 76 Loss: 0.1859947293996811
Epoch: 77 Loss: 0.18395550549030304
Epoch: 78 Loss: 0.18196186423301697
Epoch: 79 Loss: 0.18001243472099304
Epoch: 80 Loss: 0.17810605466365814
Epoch: 81 Loss: 0.1762429177761078
Epoch: 82 Loss: 0.1744219958782196
Epoch: 83 Loss: 0.1726418286561966
Epoch: 84 Loss: 0.17089907824993134
Epoch: 85 Loss: 0.16919562220573425
Epoch: 86 Loss: 0.16752909123897552
Epoch: 87 Loss: 0.16589848697185516
Epoch: 88 Loss: 0.16430248320102692
Epoch: 89 Loss: 0.16273875534534454
Epoch: 90 Loss: 0.16120752692222595
Epoch: 91 Loss: 0.159707173705101
Epoch: 92 Loss: 0.158237025141716
Epoch: 93 Loss: 0.15679675340652466
Epoch: 94 Loss: 0.1553848385810852
Epoch: 95 Loss: 0.15400277078151703
Epoch: 96 Loss: 0.15264923870563507
Epoch: 97 Loss: 0.15132266283035278
Epoch: 98 Loss: 0.15002377331256866
Epoch: 99 Loss: 0.14875109493732452

In [52]:
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5258541107177734