In [39]:
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

In [40]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [41]:
df.shape

(569, 33)

In [42]:
df.drop(['id', 'Unnamed: 32'], inplace=True, axis=1)
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [43]:
X_train, X_test, y_train, y_test = train_test_split(df.drop('diagnosis', axis=1), df['diagnosis'], test_size=0.2, random_state=42)

In [44]:
scaler = StandardScaler();
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [45]:
lebelEncoder = LabelEncoder()
y_train = lebelEncoder.fit_transform(y_train)
y_test = lebelEncoder.transform(y_test)

In [46]:
X_train_tensor = torch.tensor(X_train, dtype=torch.float32)
X_test_tensor = torch.tensor(X_test, dtype=torch.float32)
y_train_tensor = torch.tensor(y_train, dtype=torch.float32)
y_test_tensor = torch.tensor(y_test, dtype=torch.float32)

In [47]:
class CustomeDataset(Dataset):
  def __init__(self, features, labels):
    self.features = features
    self.labels = labels

  def __len__(self):
    return self.features.shape[0]

  def __getitem__(self, index):
    return self.features[index], self.labels[index]

In [48]:
train_dataset = CustomeDataset(X_train_tensor, y_train_tensor)
test_dataset = CustomeDataset(X_test_tensor, y_test_tensor)

In [49]:
train_loader = DataLoader(train_dataset, batch_size=64, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=64, shuffle=False)

In [50]:
class Model(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(num_features, 32),
        nn.ReLU(),
        nn.Linear(32, 1),
        nn.Sigmoid()
    )

  def forward(self, X):
    return self.network(X)

In [51]:
loss_function = nn.BCELoss()
epochs = 100

In [52]:
model = Model(X_train_tensor.shape[1])
optimizer = optim.Adam(model.parameters(), lr=0.001)

for epoch in range(epochs):
  for X_batch, y_batch in train_loader:
    y_pred = model.forward(X_batch)

    loss = loss_function(y_pred, y_batch.view(-1, 1))

    optimizer.zero_grad()

    loss.backward()

    optimizer.step()

    print(f'Epoch: {epoch+1}, Loss: {loss.item():.4f}')

Epoch: 1, Loss: 0.6649
Epoch: 1, Loss: 0.6326
Epoch: 1, Loss: 0.6362
Epoch: 1, Loss: 0.6437
Epoch: 1, Loss: 0.6342
Epoch: 1, Loss: 0.6126
Epoch: 1, Loss: 0.5985
Epoch: 1, Loss: 0.5846
Epoch: 2, Loss: 0.5733
Epoch: 2, Loss: 0.5837
Epoch: 2, Loss: 0.5708
Epoch: 2, Loss: 0.5816
Epoch: 2, Loss: 0.5342
Epoch: 2, Loss: 0.5254
Epoch: 2, Loss: 0.5319
Epoch: 2, Loss: 0.5684
Epoch: 3, Loss: 0.5072
Epoch: 3, Loss: 0.5367
Epoch: 3, Loss: 0.4830
Epoch: 3, Loss: 0.5113
Epoch: 3, Loss: 0.4754
Epoch: 3, Loss: 0.4997
Epoch: 3, Loss: 0.4695
Epoch: 3, Loss: 0.4404
Epoch: 4, Loss: 0.4190
Epoch: 4, Loss: 0.4649
Epoch: 4, Loss: 0.4667
Epoch: 4, Loss: 0.4596
Epoch: 4, Loss: 0.4547
Epoch: 4, Loss: 0.3988
Epoch: 4, Loss: 0.4460
Epoch: 4, Loss: 0.3821
Epoch: 5, Loss: 0.4118
Epoch: 5, Loss: 0.3829
Epoch: 5, Loss: 0.4136
Epoch: 5, Loss: 0.4084
Epoch: 5, Loss: 0.3787
Epoch: 5, Loss: 0.3739
Epoch: 5, Loss: 0.4094
Epoch: 5, Loss: 0.3168
Epoch: 6, Loss: 0.4310
Epoch: 6, Loss: 0.3740
Epoch: 6, Loss: 0.3095
Epoch: 6, Loss: 0.3105
Epoch: 6, Loss: 0.3409
Epoch: 6, Loss: 0.3463
Epoch: 6, Loss: 0.3601
Epoch: 6, Loss: 0.3119
Epoch: 7, Loss: 0.3186
Epoch: 7, Loss: 0.2830
Epoch: 7, Loss: 0.2896
Epoch: 7, Loss: 0.3670
Epoch: 7, Loss: 0.3458
Epoch: 7, Loss: 0.3092
Epoch: 7, Loss: 0.2981
Epoch: 7, Loss: 0.2282
Epoch: 8, Loss: 0.3034
Epoch: 8, Loss: 0.2715
Epoch: 8, Loss: 0.2594
Epoch: 8, Loss: 0.3095
Epoch: 8, Loss: 0.2930
Epoch: 8, Loss: 0.2749
Epoch: 8, Loss: 0.2766
Epoch: 8, Loss: 0.0894
Epoch: 9, Loss: 0.2388
Epoch: 9, Loss: 0.2668
Epoch: 9, Loss: 0.2574
Epoch: 9, Loss: 0.2282
Epoch: 9, Loss: 0.2827
Epoch: 9, Loss: 0.2766
Epoch: 9, Loss: 0.2210
Epoch: 9, Loss: 0.2244
Epoch: 10, Loss: 0.2381
Epoch: 10, Loss: 0.2359
Epoch: 10, Loss: 0.2346
Epoch: 10, Loss: 0.2299
Epoch: 10, Loss: 0.2415
Epoch: 10, Loss: 0.2044
Epoch: 10, Loss: 0.2200
Epoch: 10, Loss: 0.1660
Epoch: 11, Loss: 0.2015
Epoch: 11, Loss: 0.2043
Epoch: 11, Loss: 0.1803
Epoch: 11, Loss: 0.2057
Epoch: 11, Loss: 0.1869
Epoch: 11, Loss: 0.2605
Epoch: 11, Loss: 0.2087
Epoch: 11, Loss: 0.2589
Epoch: 12, Loss: 0.1819
Epoch: 12, Loss: 0.2116
Epoch: 12, Loss: 0.1969
Epoch: 12, Loss: 0.1546
Epoch: 12, Loss: 0.1646
Epoch: 12, Loss: 0.2069
Epoch: 12, Loss: 0.2213
Epoch: 12, Loss: 0.1130
Epoch: 13, Loss: 0.1572
Epoch: 13, Loss: 0.2116
Epoch: 13, Loss: 0.1597
Epoch: 13, Loss: 0.1632
Epoch: 13, Loss: 0.1908
Epoch: 13, Loss: 0.1722
Epoch: 13, Loss: 0.1857
Epoch: 13, Loss: 0.0831
Epoch: 14, Loss: 0.1603
Epoch: 14, Loss: 0.1726
Epoch: 14, Loss: 0.1524
Epoch: 14, Loss: 0.1474
Epoch: 14, Loss: 0.1919
Epoch: 14, Loss: 0.1911
Epoch: 14, Loss: 0.1375
Epoch: 14, Loss: 0.0579
Epoch: 15, Loss: 0.1405
Epoch: 15, Loss: 0.1787
Epoch: 15, Loss: 0.1334
Epoch: 15, Loss: 0.1602
Epoch: 15, Loss: 0.1138
Epoch: 15, Loss: 0.1561
Epoch: 15, Loss: 0.1981
Epoch: 15, Loss: 0.0759
Epoch: 16, Loss: 0.1889
Epoch: 16, Loss: 0.0870
Epoch: 16, Loss: 0.1278
Epoch: 16, Loss: 0.1676
Epoch: 16, Loss: 0.1105
Epoch: 16, Loss: 0.1507
Epoch: 16, Loss: 0.1862
Epoch: 16, Loss: 0.0739
Epoch: 17, Loss: 0.1467
Epoch: 17, Loss: 0.1703
Epoch: 17, Loss: 0.1201
Epoch: 17, Loss: 0.1445
Epoch: 17, Loss: 0.1342
Epoch: 17, Loss: 0.1067
Epoch: 17, Loss: 0.1284
Epoch: 17, Loss: 0.2066
Epoch: 18, Loss: 0.0902
Epoch: 18, Loss: 0.1713
Epoch: 18, Loss: 0.1341
Epoch: 18, Loss: 0.1214
Epoch: 18, Loss: 0.1134
Epoch: 18, Loss: 0.1289
Epoch: 18, Loss: 0.1368
Epoch: 18, Loss: 0.2674
Epoch: 19, Loss: 0.0958
Epoch: 19, Loss: 0.1557
Epoch: 19, Loss: 0.1118
Epoch: 19, Loss: 0.0979
Epoch: 19, Loss: 0.1894
Epoch: 19, Loss: 0.1037
Epoch: 19, Loss: 0.1198
Epoch: 19, Loss: 0.0956
Epoch: 20, Loss: 0.0779
Epoch: 20, Loss: 0.1021
Epoch: 20, Loss: 0.1300
Epoch: 20, Loss: 0.0937
Epoch: 20, Loss: 0.1385
Epoch: 20, Loss: 0.1340
Epoch: 20, Loss: 0.1578
Epoch: 20, Loss: 0.1404
Epoch: 21, Loss: 0.0960
Epoch: 21, Loss: 0.1532
Epoch: 21, Loss: 0.1067
Epoch: 21, Loss: 0.1245
Epoch: 21, Loss: 0.1421
Epoch: 21, Loss: 0.0889
Epoch: 21, Loss: 0.0961
Epoch: 21, Loss: 0.0817
Epoch: 22, Loss: 0.0857
Epoch: 22, Loss: 0.1504
Epoch: 22, Loss: 0.1453
Epoch: 22, Loss: 0.0635
Epoch: 22, Loss: 0.1262
Epoch: 22, Loss: 0.0657
Epoch: 22, Loss: 0.1318
Epoch: 22, Loss: 0.1530
Epoch: 23, Loss: 0.1113
Epoch: 23, Loss: 0.1032
Epoch: 23, Loss: 0.1439
Epoch: 23, Loss: 0.0894
Epoch: 23, Loss: 0.1341
Epoch: 23, Loss: 0.0857
Epoch: 23, Loss: 0.0851
Epoch: 23, Loss: 0.0546
Epoch: 24, Loss: 0.0720
Epoch: 24, Loss: 0.1637
Epoch: 24, Loss: 0.0766
Epoch: 24, Loss: 0.0607
Epoch: 24, Loss: 0.0673
Epoch: 24, Loss: 0.1154
Epoch: 24, Loss: 0.1752
Epoch: 24, Loss: 0.0320
Epoch: 25, Loss: 0.1258
Epoch: 25, Loss: 0.0983
Epoch: 25, Loss: 0.1016
Epoch: 25, Loss: 0.0768
Epoch: 25, Loss: 0.1280
Epoch: 25, Loss: 0.0820
Epoch: 25, Loss: 0.0884
Epoch: 25, Loss: 0.0930
Epoch: 26, Loss: 0.1332
Epoch: 26, Loss: 0.0548
Epoch: 26, Loss: 0.0779
Epoch: 26, Loss: 0.0709
Epoch: 26, Loss: 0.1300
Epoch: 26, Loss: 0.0999
Epoch: 26, Loss: 0.1192
Epoch: 26, Loss: 0.0385
Epoch: 27, Loss: 0.0973
Epoch: 27, Loss: 0.0964
Epoch: 27, Loss: 0.0612
Epoch: 27, Loss: 0.0946
Epoch: 27, Loss: 0.0696
Epoch: 27, Loss: 0.1733
Epoch: 27, Loss: 0.0727
Epoch: 27, Loss: 0.0437
Epoch: 28, Loss: 0.0954
Epoch: 28, Loss: 0.0918
Epoch: 28, Loss: 0.0849
Epoch: 28, Loss: 0.1263
Epoch: 28, Loss: 0.1314
Epoch: 28, Loss: 0.0772
Epoch: 28, Loss: 0.0443
Epoch: 28, Loss: 0.0124
Epoch: 29, Loss: 0.0431
Epoch: 29, Loss: 0.0617
Epoch: 29, Loss: 0.1431
Epoch: 29, Loss: 0.1165
Epoch: 29, Loss: 0.0694
Epoch: 29, Loss: 0.0887
Epoch: 29, Loss: 0.1109
Epoch: 29, Loss: 0.0175
Epoch: 30, Loss: 0.1391
Epoch: 30, Loss: 0.1173
Epoch: 30, Loss: 0.0712
Epoch: 30, Loss: 0.0409
Epoch: 30, Loss: 0.0975
Epoch: 30, Loss: 0.0528
Epoch: 30, Loss: 0.0841
Epoch: 30, Loss: 0.1576
Epoch: 31, Loss: 0.1452
Epoch: 31, Loss: 0.1083
Epoch: 31, Loss: 0.0737
Epoch: 31, Loss: 0.0608
Epoch: 31, Loss: 0.0917
Epoch: 31, Loss: 0.0354
Epoch: 31, Loss: 0.0868
Epoch: 31, Loss: 0.0305
Epoch: 32, Loss: 0.0752
Epoch: 32, Loss: 0.0794
Epoch: 32, Loss: 0.0485
Epoch: 32, Loss: 0.1336
Epoch: 32, Loss: 0.1306
Epoch: 32, Loss: 0.0407
Epoch: 32, Loss: 0.0765
Epoch: 32, Loss: 0.0691
Epoch: 33, Loss: 0.1175
Epoch: 33, Loss: 0.1095
Epoch: 33, Loss: 0.0691
Epoch: 33, Loss: 0.0394
Epoch: 33, Loss: 0.1090
Epoch: 33, Loss: 0.0628
Epoch: 33, Loss: 0.0628
Epoch: 33, Loss: 0.0719
Epoch: 34, Loss: 0.0319
Epoch: 34, Loss: 0.1677
Epoch: 34, Loss: 0.0498
Epoch: 34, Loss: 0.0711
Epoch: 34, Loss: 0.1116
Epoch: 34, Loss: 0.0825
Epoch: 34, Loss: 0.0424
Epoch: 34, Loss: 0.0709
Epoch: 35, Loss: 0.0437
Epoch: 35, Loss: 0.0997
Epoch: 35, Loss: 0.0855
Epoch: 35, Loss: 0.1036
Epoch: 35, Loss: 0.0840
Epoch: 35, Loss: 0.0709
Epoch: 35, Loss: 0.0655
Epoch: 35, Loss: 0.0066
Epoch: 36, Loss: 0.0443
Epoch: 36, Loss: 0.0944
Epoch: 36, Loss: 0.0535
Epoch: 36, Loss: 0.0812
Epoch: 36, Loss: 0.0843
Epoch: 36, Loss: 0.0543
Epoch: 36, Loss: 0.1193
Epoch: 36, Loss: 0.1158
Epoch: 37, Loss: 0.0610
Epoch: 37, Loss: 0.1181
Epoch: 37, Loss: 0.0516
Epoch: 37, Loss: 0.0834
Epoch: 37, Loss: 0.0632
Epoch: 37, Loss: 0.0997
Epoch: 37, Loss: 0.0516
Epoch: 37, Loss: 0.0380
Epoch: 38, Loss: 0.0488
Epoch: 38, Loss: 0.1469
Epoch: 38, Loss: 0.0568
Epoch: 38, Loss: 0.0844
Epoch: 38, Loss: 0.0533
Epoch: 38, Loss: 0.0500
Epoch: 38, Loss: 0.0683
Epoch: 38, Loss: 0.1329
Epoch: 39, Loss: 0.1086
Epoch: 39, Loss: 0.0620
Epoch: 39, Loss: 0.0465
Epoch: 39, Loss: 0.0411
Epoch: 39, Loss: 0.0592
Epoch: 39, Loss: 0.1115
Epoch: 39, Loss: 0.0434
Epoch: 39, Loss: 0.3776
Epoch: 40, Loss: 0.0587
Epoch: 40, Loss: 0.0275
Epoch: 40, Loss: 0.0353
Epoch: 40, Loss: 0.0422
Epoch: 40, Loss: 0.0830
Epoch: 40, Loss: 0.1080
Epoch: 40, Loss: 0.1402
Epoch: 40, Loss: 0.0616
Epoch: 41, Loss: 0.0790
Epoch: 41, Loss: 0.0519
Epoch: 41, Loss: 0.0383
Epoch: 41, Loss: 0.0487
Epoch: 41, Loss: 0.0686
Epoch: 41, Loss: 0.0478
Epoch: 41, Loss: 0.1553
Epoch: 41, Loss: 0.0522
Epoch: 42, Loss: 0.0461
Epoch: 42, Loss: 0.0724
Epoch: 42, Loss: 0.1182
Epoch: 42, Loss: 0.0568
Epoch: 42, Loss: 0.0865
Epoch: 42, Loss: 0.0407
Epoch: 42, Loss: 0.0670
Epoch: 42, Loss: 0.0065
Epoch: 43, Loss: 0.0384
Epoch: 43, Loss: 0.0421
Epoch: 43, Loss: 0.0799
Epoch: 43, Loss: 0.1462
Epoch: 43, Loss: 0.0711
Epoch: 43, Loss: 0.0749
Epoch: 43, Loss: 0.0244
Epoch: 43, Loss: 0.0326
Epoch: 44, Loss: 0.1272
Epoch: 44, Loss: 0.0362
Epoch: 44, Loss: 0.0714
Epoch: 44, Loss: 0.0433
Epoch: 44, Loss: 0.0743
Epoch: 44, Loss: 0.0519
Epoch: 44, Loss: 0.0539
Epoch: 44, Loss: 0.1391
Epoch: 45, Loss: 0.0360
Epoch: 45, Loss: 0.0390
Epoch: 45, Loss: 0.0426
Epoch: 45, Loss: 0.0353
Epoch: 45, Loss: 0.1266
Epoch: 45, Loss: 0.0819
Epoch: 45, Loss: 0.1026
Epoch: 45, Loss: 0.0171
Epoch: 46, Loss: 0.0668
Epoch: 46, Loss: 0.1304
Epoch: 46, Loss: 0.0310
Epoch: 46, Loss: 0.0373
Epoch: 46, Loss: 0.0947
Epoch: 46, Loss: 0.0505
Epoch: 46, Loss: 0.0455
Epoch: 46, Loss: 0.0239
Epoch: 47, Loss: 0.0531
Epoch: 47, Loss: 0.1144
Epoch: 47, Loss: 0.0325
Epoch: 47, Loss: 0.0431
Epoch: 47, Loss: 0.0303
Epoch: 47, Loss: 0.0597
Epoch: 47, Loss: 0.1194
Epoch: 47, Loss: 0.0021
Epoch: 48, Loss: 0.0529
Epoch: 48, Loss: 0.1510
Epoch: 48, Loss: 0.0363
Epoch: 48, Loss: 0.0575
Epoch: 48, Loss: 0.0856
Epoch: 48, Loss: 0.0399
Epoch: 48, Loss: 0.0234
Epoch: 48, Loss: 0.0010
Epoch: 49, Loss: 0.1413
Epoch: 49, Loss: 0.0383
Epoch: 49, Loss: 0.0423
Epoch: 49, Loss: 0.0551
Epoch: 49, Loss: 0.0762
Epoch: 49, Loss: 0.0414
Epoch: 49, Loss: 0.0454
Epoch: 49, Loss: 0.0115
Epoch: 50, Loss: 0.0368
Epoch: 50, Loss: 0.1055
Epoch: 50, Loss: 0.0259
Epoch: 50, Loss: 0.0293
Epoch: 50, Loss: 0.0687
Epoch: 50, Loss: 0.0460
Epoch: 50, Loss: 0.1184
Epoch: 50, Loss: 0.0437
Epoch: 51, Loss: 0.0382
Epoch: 51, Loss: 0.1426
Epoch: 51, Loss: 0.0575
Epoch: 51, Loss: 0.0402
Epoch: 51, Loss: 0.0603
Epoch: 51, Loss: 0.0615
Epoch: 51, Loss: 0.0278
Epoch: 51, Loss: 0.0177
Epoch: 52, Loss: 0.0201
Epoch: 52, Loss: 0.0490
Epoch: 52, Loss: 0.1337
Epoch: 52, Loss: 0.0885
Epoch: 52, Loss: 0.0329
Epoch: 52, Loss: 0.0622
Epoch: 52, Loss: 0.0259
Epoch: 52, Loss: 0.1133
Epoch: 53, Loss: 0.0255
Epoch: 53, Loss: 0.0277
Epoch: 53, Loss: 0.0520
Epoch: 53, Loss: 0.0368
Epoch: 53, Loss: 0.1113
Epoch: 53, Loss: 0.0414
Epoch: 53, Loss: 0.1185
Epoch: 53, Loss: 0.0695
Epoch: 54, Loss: 0.0747
Epoch: 54, Loss: 0.1294
Epoch: 54, Loss: 0.0292
Epoch: 54, Loss: 0.0277
Epoch: 54, Loss: 0.0492
Epoch: 54, Loss: 0.0624
Epoch: 54, Loss: 0.0377
Epoch: 54, Loss: 0.0416
Epoch: 55, Loss: 0.0778
Epoch: 55, Loss: 0.0505
Epoch: 55, Loss: 0.0200
Epoch: 55, Loss: 0.0773
Epoch: 55, Loss: 0.1074
Epoch: 55, Loss: 0.0404
Epoch: 55, Loss: 0.0367
Epoch: 55, Loss: 0.0018
Epoch: 56, Loss: 0.0408
Epoch: 56, Loss: 0.0422
Epoch: 56, Loss: 0.1050
Epoch: 56, Loss: 0.0683
Epoch: 56, Loss: 0.0966
Epoch: 56, Loss: 0.0355
Epoch: 56, Loss: 0.0170
Epoch: 56, Loss: 0.0008
Epoch: 57, Loss: 0.0582
Epoch: 57, Loss: 0.0329
Epoch: 57, Loss: 0.0297
Epoch: 57, Loss: 0.0394
Epoch: 57, Loss: 0.0543
Epoch: 57, Loss: 0.0217
Epoch: 57, Loss: 0.1576
Epoch: 57, Loss: 0.0715
Epoch: 58, Loss: 0.0213
Epoch: 58, Loss: 0.0498
Epoch: 58, Loss: 0.0767
Epoch: 58, Loss: 0.0991
Epoch: 58, Loss: 0.0581
Epoch: 58, Loss: 0.0465
Epoch: 58, Loss: 0.0425
Epoch: 58, Loss: 0.0237
Epoch: 59, Loss: 0.0294
Epoch: 59, Loss: 0.0739
Epoch: 59, Loss: 0.0200
Epoch: 59, Loss: 0.0336
Epoch: 59, Loss: 0.0382
Epoch: 59, Loss: 0.1030
Epoch: 59, Loss: 0.0894
Epoch: 59, Loss: 0.0403
Epoch: 60, Loss: 0.0603
Epoch: 60, Loss: 0.0369
Epoch: 60, Loss: 0.0407
Epoch: 60, Loss: 0.0387
Epoch: 60, Loss: 0.1246
Epoch: 60, Loss: 0.0329
Epoch: 60, Loss: 0.0543
Epoch: 60, Loss: 0.0013
Epoch: 61, Loss: 0.0457
Epoch: 61, Loss: 0.0291
Epoch: 61, Loss: 0.0582
Epoch: 61, Loss: 0.1320
Epoch: 61, Loss: 0.0261
Epoch: 61, Loss: 0.0388
Epoch: 61, Loss: 0.0528
Epoch: 61, Loss: 0.0090
Epoch: 62, Loss: 0.1134
Epoch: 62, Loss: 0.0371
Epoch: 62, Loss: 0.0251
Epoch: 62, Loss: 0.0639
Epoch: 62, Loss: 0.0263
Epoch: 62, Loss: 0.0517
Epoch: 62, Loss: 0.0609
Epoch: 62, Loss: 0.0194
Epoch: 63, Loss: 0.0244
Epoch: 63, Loss: 0.0168
Epoch: 63, Loss: 0.0654
Epoch: 63, Loss: 0.0392
Epoch: 63, Loss: 0.1133
Epoch: 63, Loss: 0.0704
Epoch: 63, Loss: 0.0250
Epoch: 63, Loss: 0.2026
Epoch: 64, Loss: 0.0408
Epoch: 64, Loss: 0.0484
Epoch: 64, Loss: 0.0614
Epoch: 64, Loss: 0.0847
Epoch: 64, Loss: 0.0229
Epoch: 64, Loss: 0.0603
Epoch: 64, Loss: 0.0510
Epoch: 64, Loss: 0.0361
Epoch: 65, Loss: 0.0300
Epoch: 65, Loss: 0.0535
Epoch: 65, Loss: 0.0547
Epoch: 65, Loss: 0.1336
Epoch: 65, Loss: 0.0312
Epoch: 65, Loss: 0.0451
Epoch: 65, Loss: 0.0153
Epoch: 65, Loss: 0.0527
Epoch: 66, Loss: 0.0741
Epoch: 66, Loss: 0.0245
Epoch: 66, Loss: 0.0793
Epoch: 66, Loss: 0.0457
Epoch: 66, Loss: 0.0153
Epoch: 66, Loss: 0.0644
Epoch: 66, Loss: 0.0613
Epoch: 66, Loss: 0.0039
Epoch: 67, Loss: 0.0279
Epoch: 67, Loss: 0.0403
Epoch: 67, Loss: 0.1057
Epoch: 67, Loss: 0.0137
Epoch: 67, Loss: 0.0713
Epoch: 67, Loss: 0.0625
Epoch: 67, Loss: 0.0378
Epoch: 67, Loss: 0.0184
Epoch: 68, Loss: 0.0618
Epoch: 68, Loss: 0.1044
Epoch: 68, Loss: 0.0336
Epoch: 68, Loss: 0.0382
Epoch: 68, Loss: 0.0317
Epoch: 68, Loss: 0.0250
Epoch: 68, Loss: 0.0622
Epoch: 68, Loss: 0.0082
Epoch: 69, Loss: 0.0802
Epoch: 69, Loss: 0.0445
Epoch: 69, Loss: 0.0237
Epoch: 69, Loss: 0.1107
Epoch: 69, Loss: 0.0315
Epoch: 69, Loss: 0.0133
Epoch: 69, Loss: 0.0470
Epoch: 69, Loss: 0.0393
Epoch: 70, Loss: 0.1386
Epoch: 70, Loss: 0.0463
Epoch: 70, Loss: 0.0297
Epoch: 70, Loss: 0.0412
Epoch: 70, Loss: 0.0536
Epoch: 70, Loss: 0.0210
Epoch: 70, Loss: 0.0183
Epoch: 70, Loss: 0.0289
Epoch: 71, Loss: 0.0288
Epoch: 71, Loss: 0.0627
Epoch: 71, Loss: 0.0330
Epoch: 71, Loss: 0.0821
Epoch: 71, Loss: 0.0307
Epoch: 71, Loss: 0.0144
Epoch: 71, Loss: 0.0909
Epoch: 71, Loss: 0.0460
Epoch: 72, Loss: 0.0496
Epoch: 72, Loss: 0.0287
Epoch: 72, Loss: 0.0742
Epoch: 72, Loss: 0.0144
Epoch: 72, Loss: 0.0593
Epoch: 72, Loss: 0.0820
Epoch: 72, Loss: 0.0313
Epoch: 72, Loss: 0.0527
Epoch: 73, Loss: 0.0779
Epoch: 73, Loss: 0.0164
Epoch: 73, Loss: 0.0423
Epoch: 73, Loss: 0.0576
Epoch: 73, Loss: 0.0641
Epoch: 73, Loss: 0.0612
Epoch: 73, Loss: 0.0157
Epoch: 73, Loss: 0.0578
Epoch: 74, Loss: 0.0149
Epoch: 74, Loss: 0.0306
Epoch: 74, Loss: 0.0692
Epoch: 74, Loss: 0.0917
Epoch: 74, Loss: 0.0157
Epoch: 74, Loss: 0.0846
Epoch: 74, Loss: 0.0313
Epoch: 74, Loss: 0.0017
Epoch: 75, Loss: 0.0524
Epoch: 75, Loss: 0.0164
Epoch: 75, Loss: 0.0284
Epoch: 75, Loss: 0.0587
Epoch: 75, Loss: 0.0835
Epoch: 75, Loss: 0.0297
Epoch: 75, Loss: 0.0600
Epoch: 75, Loss: 0.0570
Epoch: 76, Loss: 0.0792
Epoch: 76, Loss: 0.0283
Epoch: 76, Loss: 0.0277
Epoch: 76, Loss: 0.0466
Epoch: 76, Loss: 0.0159
Epoch: 76, Loss: 0.0713
Epoch: 76, Loss: 0.0630
Epoch: 76, Loss: 0.0086
Epoch: 77, Loss: 0.0160
Epoch: 77, Loss: 0.0391
Epoch: 77, Loss: 0.0236
Epoch: 77, Loss: 0.1418
Epoch: 77, Loss: 0.0224
Epoch: 77, Loss: 0.0371
Epoch: 77, Loss: 0.0482
Epoch: 77, Loss: 0.0187
Epoch: 78, Loss: 0.0163
Epoch: 78, Loss: 0.0507
Epoch: 78, Loss: 0.0422
Epoch: 78, Loss: 0.0218
Epoch: 78, Loss: 0.1252
Epoch: 78, Loss: 0.0269
Epoch: 78, Loss: 0.0436
Epoch: 78, Loss: 0.0056
Epoch: 79, Loss: 0.0120
Epoch: 79, Loss: 0.0626
Epoch: 79, Loss: 0.0362
Epoch: 79, Loss: 0.0449
Epoch: 79, Loss: 0.0444
Epoch: 79, Loss: 0.0284
Epoch: 79, Loss: 0.0917
Epoch: 79, Loss: 0.0358
Epoch: 80, Loss: 0.0163
Epoch: 80, Loss: 0.1227
Epoch: 80, Loss: 0.0380
Epoch: 80, Loss: 0.0551
Epoch: 80, Loss: 0.0242
Epoch: 80, Loss: 0.0130
Epoch: 80, Loss: 0.0202
Epoch: 80, Loss: 0.2928
Epoch: 81, Loss: 0.0234
Epoch: 81, Loss: 0.0491
Epoch: 81, Loss: 0.0310
Epoch: 81, Loss: 0.0289
Epoch: 81, Loss: 0.0866
Epoch: 81, Loss: 0.0527
Epoch: 81, Loss: 0.0464
Epoch: 81, Loss: 0.0034
Epoch: 82, Loss: 0.0996
Epoch: 82, Loss: 0.0449
Epoch: 82, Loss: 0.0187
Epoch: 82, Loss: 0.0379
Epoch: 82, Loss: 0.0269
Epoch: 82, Loss: 0.0557
Epoch: 82, Loss: 0.0208
Epoch: 82, Loss: 0.1071
Epoch: 83, Loss: 0.0260
Epoch: 83, Loss: 0.0245
Epoch: 83, Loss: 0.0931
Epoch: 83, Loss: 0.0467
Epoch: 83, Loss: 0.0323
Epoch: 83, Loss: 0.0460
Epoch: 83, Loss: 0.0421
Epoch: 83, Loss: 0.0278
Epoch: 84, Loss: 0.0232
Epoch: 84, Loss: 0.0259
Epoch: 84, Loss: 0.0353
Epoch: 84, Loss: 0.0146
Epoch: 84, Loss: 0.0594
Epoch: 84, Loss: 0.1227
Epoch: 84, Loss: 0.0309
Epoch: 84, Loss: 0.0088
Epoch: 85, Loss: 0.0235
Epoch: 85, Loss: 0.1183
Epoch: 85, Loss: 0.0449
Epoch: 85, Loss: 0.0209
Epoch: 85, Loss: 0.0260
Epoch: 85, Loss: 0.0235
Epoch: 85, Loss: 0.0509
Epoch: 85, Loss: 0.0198
Epoch: 86, Loss: 0.0960
Epoch: 86, Loss: 0.0452
Epoch: 86, Loss: 0.0428
Epoch: 86, Loss: 0.0571
Epoch: 86, Loss: 0.0193
Epoch: 86, Loss: 0.0238
Epoch: 86, Loss: 0.0225
Epoch: 86, Loss: 0.0018
Epoch: 87, Loss: 0.0417
Epoch: 87, Loss: 0.0861
Epoch: 87, Loss: 0.0746
Epoch: 87, Loss: 0.0157
Epoch: 87, Loss: 0.0200
Epoch: 87, Loss: 0.0166
Epoch: 87, Loss: 0.0430
Epoch: 87, Loss: 0.0567
Epoch: 88, Loss: 0.1089
Epoch: 88, Loss: 0.0541
Epoch: 88, Loss: 0.0429
Epoch: 88, Loss: 0.0366
Epoch: 88, Loss: 0.0120
Epoch: 88, Loss: 0.0273
Epoch: 88, Loss: 0.0177
Epoch: 88, Loss: 0.0027
Epoch: 89, Loss: 0.0358
Epoch: 89, Loss: 0.0154
Epoch: 89, Loss: 0.0235
Epoch: 89, Loss: 0.0667
Epoch: 89, Loss: 0.0373
Epoch: 89, Loss: 0.0384
Epoch: 89, Loss: 0.0784
Epoch: 89, Loss: 0.0175
Epoch: 90, Loss: 0.0877
Epoch: 90, Loss: 0.0533
Epoch: 90, Loss: 0.0412
Epoch: 90, Loss: 0.0180
Epoch: 90, Loss: 0.0322
Epoch: 90, Loss: 0.0467
Epoch: 90, Loss: 0.0161
Epoch: 90, Loss: 0.0057
Epoch: 91, Loss: 0.0363
Epoch: 91, Loss: 0.0482
Epoch: 91, Loss: 0.0126
Epoch: 91, Loss: 0.0676
Epoch: 91, Loss: 0.0419
Epoch: 91, Loss: 0.0522
Epoch: 91, Loss: 0.0328
Epoch: 91, Loss: 0.0176
Epoch: 92, Loss: 0.0129
Epoch: 92, Loss: 0.0303
Epoch: 92, Loss: 0.0545
Epoch: 92, Loss: 0.0311
Epoch: 92, Loss: 0.0290
Epoch: 92, Loss: 0.0234
Epoch: 92, Loss: 0.1044
Epoch: 92, Loss: 0.0601
Epoch: 93, Loss: 0.0607
Epoch: 93, Loss: 0.0926
Epoch: 93, Loss: 0.0176
Epoch: 93, Loss: 0.0286
Epoch: 93, Loss: 0.0126
Epoch: 93, Loss: 0.0560
Epoch: 93, Loss: 0.0165
Epoch: 93, Loss: 0.0417
Epoch: 94, Loss: 0.0137
Epoch: 94, Loss: 0.0336
Epoch: 94, Loss: 0.0239
Epoch: 94, Loss: 0.0377
Epoch: 94, Loss: 0.0666
Epoch: 94, Loss: 0.0739
Epoch: 94, Loss: 0.0250
Epoch: 94, Loss: 0.1179
Epoch: 95, Loss: 0.0267
Epoch: 95, Loss: 0.0797
Epoch: 95, Loss: 0.0349
Epoch: 95, Loss: 0.0196
Epoch: 95, Loss: 0.0509
Epoch: 95, Loss: 0.0188
Epoch: 95, Loss: 0.0210
Epoch: 95, Loss: 0.3054
Epoch: 96, Loss: 0.0264
Epoch: 96, Loss: 0.0268
Epoch: 96, Loss: 0.0570
Epoch: 96, Loss: 0.0893
Epoch: 96, Loss: 0.0130
Epoch: 96, Loss: 0.0259
Epoch: 96, Loss: 0.0367
Epoch: 96, Loss: 0.0612
Epoch: 97, Loss: 0.0384
Epoch: 97, Loss: 0.0836
Epoch: 97, Loss: 0.0174
Epoch: 97, Loss: 0.0353
Epoch: 97, Loss: 0.0130
Epoch: 97, Loss: 0.0295
Epoch: 97, Loss: 0.0626
Epoch: 97, Loss: 0.0055
Epoch: 98, Loss: 0.0463
Epoch: 98, Loss: 0.0894
Epoch: 98, Loss: 0.0284
Epoch: 98, Loss: 0.0176
Epoch: 98, Loss: 0.0239
Epoch: 98, Loss: 0.0509
Epoch: 98, Loss: 0.0181
Epoch: 98, Loss: 0.0341
Epoch: 99, Loss: 0.0508
Epoch: 99, Loss: 0.0356
Epoch: 99, Loss: 0.0204
Epoch: 99, Loss: 0.0259
Epoch: 99, Loss: 0.0939
Epoch: 99, Loss: 0.0265
Epoch: 99, Loss: 0.0156
Epoch: 99, Loss: 0.0628
Epoch: 100, Loss: 0.0215
Epoch: 100, Loss: 0.0195
Epoch: 100, Loss: 0.0687
Epoch: 100, Loss: 0.0602
Epoch: 100, Loss: 0.0363
Epoch: 100, Loss: 0.0269
Epoch: 100, Loss: 0.0394
Epoch: 100, Loss: 0.0036

In [53]:
model.eval()

correct = 0
total = 0

with torch.no_grad():

    for X_batch, y_batch in test_loader:

        y_pred = model(X_batch)

        y_pred = (y_pred > 0.5).float()

        correct += (
            y_pred.squeeze()
            ==
            y_batch
        ).sum().item()

        total += y_batch.size(0)

print(f'Accuracy: {correct/total:.4f}')

Accuracy: 0.9825